/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FTP_Interface;

import java.awt.Color;

/**
 *
 * @author jojoj
 */
public class ClientWindow extends javax.swing.JFrame {

    /**
     * Creates new form ClientWindow
     */
    public ClientWindow() {
        initComponents();
        this.setLocationRelativeTo(null);
        setBackground(new Color(0.0f,0.0f,0.0f,0.0f));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        DeleteButon = new javax.swing.JButton();
        UploadBuuton = new javax.swing.JButton();
        renameButton = new javax.swing.JButton();
        DownloadButton = new javax.swing.JButton();
        main = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 90, 170, 40));

        AddButton.setContentAreaFilled(false);
        AddButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AddButtonMouseClicked(evt);
            }
        });
        getContentPane().add(AddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 90, 30));

        DeleteButon.setContentAreaFilled(false);
        DeleteButon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(DeleteButon, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 340, 120, 40));

        UploadBuuton.setContentAreaFilled(false);
        UploadBuuton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        UploadBuuton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                UploadBuutonMouseClicked(evt);
            }
        });
        getContentPane().add(UploadBuuton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 120, 40));

        renameButton.setContentAreaFilled(false);
        renameButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(renameButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 220, 120, 50));

        DownloadButton.setContentAreaFilled(false);
        DownloadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(DownloadButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 150, 50));

        main.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FTP_Images/Cliente panel.png"))); // NOI18N
        getContentPane().add(main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AddButtonMouseClicked
        // TODO add your handling code here:
        RenameFilesWindow RenamePanel = new RenameFilesWindow();
        RenamePanel.setVisible(true);
        ServerWindow ServerPanel = new ServerWindow();
        ServerPanel.dispose();
        this.dispose();
        ServerPanel.dispose();
    }//GEN-LAST:event_AddButtonMouseClicked

    DirectorySWindow DirecSPanel = new DirectorySWindow();
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
       //for (double i=0.0;i<=1.0;i = i+ 0.1){
        
        //    String val = i+ "";
        //    float f = Float.valueOf(val);
        //    this.setOpacity(f);
        //    try{
            
        //        Thread.sleep(50);
        //    }
        //    catch (Exception e){}
            
        //}

    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void UploadBuutonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UploadBuutonMouseClicked
        // TODO add your handling code here:
        DirecSPanel.setVisible(true);
    }//GEN-LAST:event_UploadBuutonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JButton DeleteButon;
    private javax.swing.JButton DownloadButton;
    private javax.swing.JButton UploadBuuton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel main;
    private javax.swing.JButton renameButton;
    // End of variables declaration//GEN-END:variables
}
